In [2]:
import torch
torch.__version__

'2.13.0+cpu'

In [ ]:
import torch
import numpy as np

## 一、 创建张量

In [24]:
# 通过列表创建张量
t1 = torch.tensor([1, 2])
t1

tensor([1, 2])

In [25]:
# 通过元组创建张量
t2 = torch.tensor((2,3))
t2

tensor([2, 3])

In [26]:
# 通过数组创建张量
a = np.array((1, 2))
t3 = torch.tensor(a)
t3

tensor([1, 2])

## 二、 张量的类型

In [27]:
# 张量的类型，创建整型数组时，张量默认int64
type(t1)
type(t3)
t1.dtype
t3.dtype

torch.int64

In [28]:
# 创建浮点型张量时，张量默认float32
torch.tensor([1.1, 2.2]).dtype

torch.float32

In [29]:
# array默认float64
torch.tensor(np.array([1, 2])).dtype

torch.int64

In [32]:
# 创建指定类型的张量
torch.tensor([1.1, 1.2], dtype = torch.int16)

tensor([1, 1], dtype=torch.int16)

## 三、 张量类型的转化

In [33]:
# 隐式转换，同一张量内部数据类型必须相同
torch.tensor([1.1, 2]).dtype

# 显示转化
t1.float()#32位浮点
t1.double()#64位浮点
t1.int()#32位整型
t1.short()#16位整型

tensor([1, 2], dtype=torch.int16)

## 四、 张量的维度

In [22]:
t1 = torch.tensor([1, 2, 3])
# 使用ndim查看维度
t.ndim

1

In [19]:
# 使用shape查看形状
t1.shape

torch.Size([3])

In [30]:
t1.size()
len(t)

3

In [31]:
# 返回总共有几个数
t1.numel()

3

In [36]:
# 用list的list创建二维张量
t2 = torch.tensor([[1,2,3], [4,5,6]])
t2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [37]:
t2.ndim

2

In [38]:
t2.shape

torch.Size([2, 3])

In [39]:
t2.size()

torch.Size([2, 3])

In [41]:
t2.numel()

6

In [42]:
len(t2)# 由2个三维张量构成

2

### 4.1 零维张量：该类型张量只包含一个元素，但不是一个单独的数，类似于标量
作用：tensor(1)可以放到GPU上运算，而数字1不可以

In [45]:
t0 = torch.tensor(1)
t0

tensor(1)

In [47]:
# 不同于一维张量
t1 = torch.tensor([1])
t1

tensor([1])

### 4.2高维张量
三维及三维以上的张量，可以理解为二维数组或矩阵的集合

In [48]:
a1 = np.array([[1,2,3], [4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
a2 = np.array([[1,3,5],[2,4,6]])
a2

array([[1, 3, 5],
       [2, 4, 6]])

In [50]:
t3 = torch.tensor([a1, a2])
t3

/tmp/ipykernel_677/1569380356.py:1: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_new.cpp:252.)
  t3 = torch.tensor([a1, a2])


tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 3, 5],
         [2, 4, 6]]])

In [55]:
t3.ndim

3

In [52]:
len(t3)

2

In [54]:
t3.shape  #包含两个两行三列的矩阵

torch.Size([2, 2, 3])

## 五、 张量的形变
张量作为数字的结构化集合，其结构也是可以根据实际需求灵活调整的

### 5.1flatten拉平：将任意维张量转化为一维张量

In [57]:
t2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [58]:
t2.flatten()

tensor([1, 2, 3, 4, 5, 6])

In [59]:
t3

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 3, 5],
         [2, 4, 6]]])

In [60]:
t3.flatten()

tensor([1, 2, 3, 4, 5, 6, 1, 3, 5, 2, 4, 6])

如果对零维张量使用flatten，会转化为一维张量

In [61]:
t0

tensor(1)

In [62]:
t0.flatten()

tensor([1])

### 5.2reshape方法：任意变形

In [64]:
t2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [66]:
t2.reshape(6, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [70]:
# 用reshape转一维张量
t2.reshape(6)

tensor([1, 2, 3, 4, 5, 6])

In [73]:
# 转化为二维张量

In [76]:
t1 = torch.tensor([1, 2])
t1

tensor([1, 2])

In [77]:
t1.reshape(1, 2) # 生成包含一个两个元素的二维张量

tensor([[1, 2]])

In [78]:
# 转化为三维张量
t1.reshape([1, 1, 2])

tensor([[[1, 2]]])

## 六、 张量运算
分为逐元素运算和矩阵乘法

### 6.1逐元素运算：加减乘除
前提：两个张量的形状必须完全相同，或者满足广播机制

In [4]:
a = torch.tensor([[1,2,3], [4,5,6]])
b = torch.tensor([[10,20,30],[40,50,60]])

# 加法
add_r = a + b
add_r

tensor([[11, 22, 33],
        [44, 55, 66]])

In [5]:
# 减法
sub_r = a- b
sub_r

tensor([[ -9, -18, -27],
        [-36, -45, -54]])

In [6]:
# 乘法，逐元素相乘
mul_r = a * b
mul_r

tensor([[ 10,  40,  90],
        [160, 250, 360]])

In [7]:
# 除法
div_r = b/a
div_r

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [8]:
# 广播机制示例：形状 (2,3) 与 (1,3) 相加，会自动复制第一行
c = torch.tensor([[100, 200, 300]])
broadcast_add = a + c

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


### 6.2矩阵乘法
- 维度规则：(m × n) 与 (n × p) 相乘，得到 (m × p)。
- 核心要求：左张量的最后一维（列数）必须等于右张量的倒数第二维（行数）。
- 常用方法：**torch.mm**（仅限2D）、**torch.matmul**（推荐，支持高维批量计算）、或直接用 **@** 操作符。

In [ ]:
# 创建两个符合矩阵乘法规则的张量
# A 形状 (2, 3), B 形状 (3, 4) -> 结果形状 (2, 4)
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
B = torch.tensor([[7, 8, 9, 10],
                  [11, 12, 13, 14],
                  [15, 16, 17, 18]])

In [11]:
# 三种写法完全等价（推荐使用 @ 或 matmul）
# torch.mm
matmul_result_1 = torch.mm(A, B)      # 仅适用于2D
matmul_result_1

tensor([[ 74,  80,  86,  92],
        [173, 188, 203, 218]])

In [12]:
# torch.matmul
matmul_result_2 = torch.matmul(A, B)  # 通用推荐
matmul_result_2

tensor([[ 74,  80,  86,  92],
        [173, 188, 203, 218]])

In [14]:
# @
matmul_result_3 = A @ B               # Python内置运算符，最简洁
matmul_result_3

tensor([[ 74,  80,  86,  92],
        [173, 188, 203, 218]])

### 6.3 高维张量的矩阵乘法
- 在实际深度学习（如Transformer）中，我们经常处理 Batch（批次） 数据。**torch.matmul** 支持批量矩阵乘法。
- 规则：前几维（Batch维度）必须相同，或者符合广播机制。只对最后两维进行矩阵乘法。

In [15]:
# 批量大小 2，每个批次内有 3x4 和 4x5 的矩阵
# 形状: (Batch, 行, 列)
X = torch.randn(2, 3, 4)  # 2个 3x4 的矩阵
Y = torch.randn(2, 4, 5)  # 2个 4x5 的矩阵

# 批量矩阵乘法，结果形状为 (2, 3, 5)
batch_result = torch.matmul(X, Y)  # 或 X @ Y
batch_result

tensor([[[-3.8478,  3.6604,  0.0427, -3.1242,  1.8946],
         [-0.1339, -1.5491, -2.4322,  2.0584,  1.7585],
         [-1.4811,  1.0842, -0.6685, -0.7115, -1.0334]],

        [[ 2.0358,  2.6610,  2.0700,  1.4233,  1.4457],
         [ 0.4134,  0.2825,  0.6070,  0.6088,  0.5599],
         [ 1.4005, -0.2466,  1.7259,  0.7933, -0.6348]]])

## 七、自动微分基础
其底层原理是动态计算图（Dynamic Computation Graph）：当你执行张量运算时，PyTorch 会像“录像机”一样把每一步操作都记录下来，构建出一个有向无环图（DAG）。调用 backward() 时，就沿着这个图反向传播，用链式法则求导。

### 7.1设置requires_grad(开启追踪）
只有叶子张量（即用户直接创建的张量）开启了 requires_grad=True，梯度才会被计算和存储。中间运算结果的梯度默认会被释放以节省内存。

In [18]:
# 方式一：创建时直接开启
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
w = torch.tensor([0.2, 0.3, 0.4], requires_grad=True)

In [19]:
# 方式二：创建后修改（常用于冻结/解冻网络层）
b = torch.tensor([0.1, 0.2, 0.3])
b.requires_grad_(True)  

tensor([0.1000, 0.2000, 0.3000], requires_grad=True)

### 7.2构建计算图（前向传播）
对 x 和 w 进行运算时，计算图就在这一瞬间动态构建好了。每个中间结果都会有一个 grad_fn 属性，指向它是由哪个操作生成的

In [20]:
# 执行前向运算（构建计算图）
y = x * w              # 逐元素相乘，中间节点，grad_fn=MultiplyBackward
z = y.sum()            # 求和，得到标量，grad_fn=SumBackward

print("x 是叶子节点，grad_fn:", x.grad_fn)   # None
print("y 是中间节点，grad_fn:", y.grad_fn)   # <MulBackward0 object>
print("z 是标量结果，grad_fn:", z.grad_fn)   # <SumBackward0 object>

x 是叶子节点，grad_fn: None
y 是中间节点，grad_fn: <MulBackward0 object at 0x7202cf5b3e50>
z 是标量结果，grad_fn: <SumBackward0 object at 0x7202cf5b3a90>


### 7.3 调用backward（）反向传播求导
- 如果结果是标量（0维），直接调用 z.backward() 即可。
- 如果结果是向量，需要传入一个与结果形状相同的权重张量（即 gradient 参数），相当于计算雅可比向量积（Jacobian-vector product）。这通常是为了将向量转化为标量损失。

In [ ]:
# 情况一：对标量求导
z.backward()  # 因为 z 是标量，无需传参

In [21]:
# 情况二：如果 y 是向量，想求 y 对 x 的导数，需要传入全1向量（相当于求导数和）
# y.backward(torch.ones_like(y)) 

### 7.4 查看 grad（获取梯度）
梯度会累积在叶子张量的 .grad 属性中

In [22]:
print("x 的梯度 (∂z/∂x):", x.grad)   # 输出: tensor([0.2000, 0.3000, 0.4000])
print("w 的梯度 (∂z/∂w):", w.grad)   # 输出: tensor([1.0000, 2.0000, 3.0000])

x 的梯度 (∂z/∂x): None
w 的梯度 (∂z/∂w): None


### 7.5推理时必须禁用梯度追踪

In [ ]:
# 推理时的标准写法
with torch.no_grad():
    pred = model(test_input)  # 此时不会构建计算图，省显存、加速